Archivo que permite configurar opciones de 
financiamiento para el proyecto, 
añadiendo enlaces a plataformas de donaciones como 
GitHub Sponsors, Patreon, OpenCollective, etc.

github: [tuusuario]
patreon: tuusuario
open_collective: tuusuario
